// Mock data for Admin UI development
import type { Admin, Notice, ConfigEntry, AdminNavItem } from '../types';

export const mockAdmin: Admin = {
  id: '1',
  userId: 'user-admin-1',
  name: 'Admin User',
  email: 'admin@infyjobs.com',
  role: 'super_admin',
  createdAt: new Date('2023-01-01'),
  updatedAt: new Date('2024-11-01'),
};

export const mockNotices: Notice[] = [
  {
    id: '1',
    title: 'Platform Maintenance Scheduled',
    description: 'The platform will undergo scheduled maintenance on November 15th from 2 AM to 4 AM EST.',
    isActive: true,
    targetAudience: 'all',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: '2',
    title: 'New Features Released',
    description: 'We have released new dashboard features for candidates. Check out the improved profile management!',
    isActive: true,
    targetAudience: 'candidates',
    createdAt: new Date('2024-10-28'),
    updatedAt: new Date('2024-10-28'),
  },
  {
    id: '3',
    title: 'Employer Verification Process',
    description: 'All employers must complete the verification process to post new jobs.',
    isActive: true,
    targetAudience: 'employers',
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: '4',
    title: 'Holiday Schedule',
    description: 'Our support team will have limited availability during the holiday season.',
    isActive: false,
    targetAudience: 'all',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-22'),
  },
];

export const mockMaritalStatuses: ConfigEntry[] = [
  {
    id: '1',
    type: 'maritalStatus',
    value: 'Single',
    isActive: true,
    usageCount: 1250,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    type: 'maritalStatus',
    value: 'Married',
    isActive: true,
    usageCount: 890,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    type: 'maritalStatus',
    value: 'Divorced',
    isActive: true,
    usageCount: 145,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '4',
    type: 'maritalStatus',
    value: 'Widowed',
    isActive: true,
    usageCount: 32,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockSkills: ConfigEntry[] = [
  {
    id: '1',
    type: 'skills',
    value: 'JavaScript',
    isActive: true,
    usageCount: 2340,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    type: 'skills',
    value: 'TypeScript',
    isActive: true,
    usageCount: 1890,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    type: 'skills',
    value: 'React',
    isActive: true,
    usageCount: 2100,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '4',
    type: 'skills',
    value: 'Node.js',
    isActive: true,
    usageCount: 1650,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '5',
    type: 'skills',
    value: 'Python',
    isActive: true,
    usageCount: 1420,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockSalaryPeriods: ConfigEntry[] = [
  {
    id: '1',
    type: 'salaryPeriods',
    value: 'Hourly',
    isActive: true,
    usageCount: 450,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    type: 'salaryPeriods',
    value: 'Monthly',
    isActive: true,
    usageCount: 1200,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    type: 'salaryPeriods',
    value: 'Annual',
    isActive: true,
    usageCount: 2800,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockIndustries: ConfigEntry[] = [
  {
    id: '1',
    type: 'industries',
    value: 'Technology',
    isActive: true,
    usageCount: 3200,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    type: 'industries',
    value: 'Healthcare',
    isActive: true,
    usageCount: 1850,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    type: 'industries',
    value: 'Finance',
    isActive: true,
    usageCount: 1620,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '4',
    type: 'industries',
    value: 'Education',
    isActive: true,
    usageCount: 980,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '5',
    type: 'industries',
    value: 'Retail',
    isActive: true,
    usageCount: 1240,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockCompanySizes: ConfigEntry[] = [
  {
    id: '1',
    type: 'companySizes',
    value: '1-10',
    isActive: true,
    usageCount: 450,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    type: 'companySizes',
    value: '11-50',
    isActive: true,
    usageCount: 680,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    type: 'companySizes',
    value: '51-200',
    isActive: true,
    usageCount: 520,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '4',
    type: 'companySizes',
    value: '201-500',
    isActive: true,
    usageCount: 340,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '5',
    type: 'companySizes',
    value: '501-1000',
    isActive: true,
    usageCount: 180,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '6',
    type: 'companySizes',
    value: '1000+',
    isActive: true,
    usageCount: 120,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockAdminNavItems: AdminNavItem[] = [
  {
    label: 'Dashboard',
    path: '/admin/dashboard',
    icon: 'LayoutDashboard',
  },
  {
    label: 'Employers',
    path: '/admin/employers',
    icon: 'Building2',
  },
  {
    label: 'Admins',
    path: '/admin/admins',
    icon: 'Shield',
  },
  {
    label: 'Candidates',
    path: '/admin/candidates',
    icon: 'Users',
  },
  {
    label: 'Jobs',
    path: '/admin/jobs',
    icon: 'Briefcase',
  },
  {
    label: 'Blogs',
    path: '/admin/blogs',
    icon: 'FileText',
  },
  {
    label: 'Subscriptions',
    path: '/admin/subscriptions',
    icon: 'CreditCard',
  },
  {
    label: 'Subscribers',
    path: '/admin/subscribers',
    icon: 'Mail',
  },
  {
    label: 'Countries',
    path: '/admin/countries',
    icon: 'Globe',
  },
  {
    label: 'General',
    path: '/admin/config',
    icon: 'Settings',
  },
  {
    label: 'CMS',
    path: '/admin/notices',
    icon: 'Bell',
  },
];
