// Mock data for Employer UI development
import type { 
  Employer, 
  EmployerStats, 
  Job, 
  JobStage, 
  ApplicationTrend 
} from '../types';

export const mockEmployer: Employer = {
  id: '1',
  userId: 'user-emp-1',
  name: 'Tech Corp',
  email: 'contact@techcorp.com',
  phone: '+1 (555) 987-6543',
  ceoName: 'Jane Smith',
  industry: 'Technology',
  ownershipType: 'Private',
  companySize: '100-500',
  establishedIn: 2015,
  employerDetails: '<p>Tech Corp is a leading technology company specializing in innovative software solutions.</p>',
  country: 'United States',
  state: 'California',
  city: 'San Francisco',
  location: '456 Tech Avenue, San Francisco, CA 94102',
  secondOfficeLocation: '789 Innovation Drive, Austin, TX 78701',
  numberOfOffices: 2,
  websiteUrl: 'https://techcorp.com',
  fax: '+1 (555) 987-6544',
  socialMedia: {
    facebook: 'https://facebook.com/techcorp',
    twitter: 'https://twitter.com/techcorp',
    linkedin: 'https://linkedin.com/company/techcorp',
  },
  isFeatured: true,
  createdAt: new Date('2023-01-01'),
  updatedAt: new Date('2024-11-01'),
};

export const mockEmployerStats: EmployerStats = {
  totalJobs: 24,
  liveJobs: 12,
  pausedJobs: 5,
  closedJobs: 7,
  followers: 1250,
  totalApplications: 486,
};

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    employerId: '1',
    title: 'Senior Frontend Developer',
    description: 'We are looking for an experienced frontend developer...',
    requirements: ['5+ years React experience', 'TypeScript proficiency'],
    responsibilities: ['Build user interfaces', 'Collaborate with design team'],
    industry: 'Technology',
    functionalArea: 'Software Development',
    careerLevel: 'Senior',
    experience: 5,
    salaryMin: 90000,
    salaryMax: 120000,
    salaryCurrency: 'USD',
    salaryPeriod: 'Annual',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    status: 'active',
    isFeatured: true,
    expiryDate: new Date('2024-12-31'),
    applicationCount: 45,
    viewCount: 320,
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'job-2',
    employerId: '1',
    title: 'Backend Engineer',
    description: 'Join our backend team to build scalable APIs...',
    requirements: ['Node.js expertise', 'Database design'],
    responsibilities: ['Design APIs', 'Optimize performance'],
    industry: 'Technology',
    functionalArea: 'Software Development',
    careerLevel: 'Mid-Level',
    experience: 3,
    salaryMin: 80000,
    salaryMax: 100000,
    salaryCurrency: 'USD',
    salaryPeriod: 'Annual',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    status: 'active',
    isFeatured: false,
    expiryDate: new Date('2024-12-15'),
    applicationCount: 32,
    viewCount: 215,
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: 'job-3',
    employerId: '1',
    title: 'DevOps Engineer',
    description: 'Help us build and maintain our infrastructure...',
    requirements: ['AWS experience', 'CI/CD pipelines'],
    responsibilities: ['Manage infrastructure', 'Automate deployments'],
    industry: 'Technology',
    functionalArea: 'DevOps',
    careerLevel: 'Senior',
    experience: 5,
    salaryMin: 95000,
    salaryMax: 125000,
    salaryCurrency: 'USD',
    salaryPeriod: 'Annual',
    country: 'United States',
    state: 'Texas',
    city: 'Austin',
    status: 'paused',
    isFeatured: false,
    expiryDate: new Date('2024-11-30'),
    applicationCount: 18,
    viewCount: 142,
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'job-4',
    employerId: '1',
    title: 'Product Manager',
    description: 'Lead product development initiatives...',
    requirements: ['Product management experience', 'Agile methodology'],
    responsibilities: ['Define product roadmap', 'Work with stakeholders'],
    industry: 'Technology',
    functionalArea: 'Product Management',
    careerLevel: 'Senior',
    experience: 6,
    salaryMin: 100000,
    salaryMax: 130000,
    salaryCurrency: 'USD',
    salaryPeriod: 'Annual',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    status: 'suspended',
    isFeatured: false,
    expiryDate: new Date('2024-11-20'),
    applicationCount: 28,
    viewCount: 198,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'job-5',
    employerId: '1',
    title: 'UX Designer',
    description: 'Create beautiful and intuitive user experiences...',
    requirements: ['Figma proficiency', 'User research skills'],
    responsibilities: ['Design interfaces', 'Conduct user testing'],
    industry: 'Technology',
    functionalArea: 'Design',
    careerLevel: 'Mid-Level',
    experience: 3,
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    salaryPeriod: 'Annual',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    status: 'closed',
    isFeatured: false,
    expiryDate: new Date('2024-10-31'),
    applicationCount: 52,
    viewCount: 387,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-10-31'),
  },
];

export const mockJobStages: JobStage[] = [
  {
    id: 'stage-1',
    employerId: '1',
    name: 'Application Review',
    description: 'Initial review of candidate applications',
    order: 1,
    isDefault: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'stage-2',
    employerId: '1',
    name: 'Phone Screening',
    description: 'Brief phone call to assess basic qualifications',
    order: 2,
    isDefault: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'stage-3',
    employerId: '1',
    name: 'Technical Interview',
    description: 'In-depth technical assessment',
    order: 3,
    isDefault: false,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15'),
  },
  {
    id: 'stage-4',
    employerId: '1',
    name: 'Team Interview',
    description: 'Meet with potential team members',
    order: 4,
    isDefault: false,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15'),
  },
  {
    id: 'stage-5',
    employerId: '1',
    name: 'Final Interview',
    description: 'Interview with hiring manager',
    order: 5,
    isDefault: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'stage-6',
    employerId: '1',
    name: 'Offer',
    description: 'Extend job offer to candidate',
    order: 6,
    isDefault: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockApplicationTrends: ApplicationTrend[] = [
  { date: new Date('2024-10-01'), count: 12 },
  { date: new Date('2024-10-02'), count: 15 },
  { date: new Date('2024-10-03'), count: 18 },
  { date: new Date('2024-10-04'), count: 14 },
  { date: new Date('2024-10-05'), count: 10 },
  { date: new Date('2024-10-06'), count: 8 },
  { date: new Date('2024-10-07'), count: 22 },
  { date: new Date('2024-10-08'), count: 25 },
  { date: new Date('2024-10-09'), count: 20 },
  { date: new Date('2024-10-10'), count: 16 },
  { date: new Date('2024-10-11'), count: 19 },
  { date: new Date('2024-10-12'), count: 14 },
  { date: new Date('2024-10-13'), count: 11 },
  { date: new Date('2024-10-14'), count: 24 },
  { date: new Date('2024-10-15'), count: 28 },
  { date: new Date('2024-10-16'), count: 21 },
  { date: new Date('2024-10-17'), count: 17 },
  { date: new Date('2024-10-18'), count: 19 },
  { date: new Date('2024-10-19'), count: 13 },
  { date: new Date('2024-10-20'), count: 9 },
  { date: new Date('2024-10-21'), count: 26 },
  { date: new Date('2024-10-22'), count: 30 },
  { date: new Date('2024-10-23'), count: 23 },
  { date: new Date('2024-10-24'), count: 18 },
  { date: new Date('2024-10-25'), count: 20 },
  { date: new Date('2024-10-26'), count: 15 },
  { date: new Date('2024-10-27'), count: 12 },
  { date: new Date('2024-10-28'), count: 27 },
  { date: new Date('2024-10-29'), count: 31 },
  { date: new Date('2024-10-30'), count: 24 },
];
